name: Docker Build and Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devsecops-demo .

      - name: Scan Docker Image With Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-demo
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
